name: eslint
on:
  - push
  
jobs:
  build:    
    
      runs-on: ubuntu-latest   
       
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
      
      - uses: actions/checkout@v1
      - name: Eslint
        run: 
          make install lint        
        
        env:
          CI: true
