name: eslint
on:
  - push
  
jobs:
  build:    
    
      runs-on: ubuntu-latest   
       
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      
      - name: Eslint
        run: 
          make install lint
      
      - name: Babel
        run:
          make build   
        
        env:
          CI: true
